{
 "title": "Dashboard",
 "description": "All the dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Books Stocks by Name",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT Stock,Name FROM books",
     "rawQueryText": "SELECT Stock,Name FROM books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cds Price by Name",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT Price,Name FROM Cds",
     "rawQueryText": "SELECT Price,Name FROM Cds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Electronics Price by Name",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT Price,Name FROM Electronics",
     "rawQueryText": "SELECT Price,Name FROM Electronics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Books Price by Name",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT Price,Name FROM books",
     "rawQueryText": "SELECT Price,Name FROM books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cds Stocks by Name",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT Stock,Name FROM Cds",
     "rawQueryText": "SELECT Stock,Name FROM Cds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Electronics Stock by Name",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT Stock,Name FROM Electronics",
     "rawQueryText": "SELECT Stock,Name FROM Electronics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}